dist: xenial
language: python
python:
- '3.7'
cache: pip
install:
- pip install flake8 pylint pytest pytest-cov pytest-asyncio aiohttp async_timeout
  voluptuous
script:
- flake8 solax tests
- pylint -d 'C0111' solax tests
- pytest --cov=solax --cov-fail-under=100 --cov-branch --cov-report=term-missing
deploy:
  provider: pypi
  user: squishykid
  password:
    secure: haZvoMACLkn1nxTn6BHw3iWooPBNlbENlNgMFLOoDyYpZy+FzXLi5Ncg2MkJ7FW6bXJMBeTEuGEEvyiU4/Y5y55O7Jj3BLpsltZrwfQ9YJV9xYQLhteP171IOtzJryS9CvRabqlhZoO2jRo75THtWy7MG7I4mODH2T2gt6fUOnsiL9vawp6QqAnZpRLpU+lKx82xoGIEf4hMpvTnOylvUOZSqDCbplff9+RgCPjYYo748DJGWe2LwoGzQpDiq7LuJXp0zQRYuXm3TOPvXGXVgRESJfFzlo9TX+XHJqTI0bYSwK/gRBCmWzyaZhkF1bgkHYOxO2qBW3jVSracZc0XTWRoJ/ngX0ndSaKwRCTgrraeg70sKQwb2LjXDl6w1WTpSDcde/xRi714Kjg8vLVpxjWWX+rjp8ZDHj5h6BcbAGf8XJrydG3UJa8n/4sfsmNfl/0eRzMdNfGylAKygPu0luJs1DMzfbiyTroVolrQRdQ7jyag8JPDTDiI59VN9TEIRj7o8aPY//jeGQBiSDAUqsIE1ddgEeGOz1LHgTP6cEc0VbdmIdmD8kuh13mL5Vz+fBAJ5r2vetIP4N6ynNGhTz/yDtf9bg91gcA97ugKl48X4NdJ0N2eqV0+PkzSt3RFF/W+NwJlj8yg3hTJupwkxGZWs8Z4Dg9/ZCrbjSIXa08=
  on:
    tags: true